print('===== QUESTÃO 19 =====')
h1 = int(input('Digite a idade do primeiro homem: '))
h2 = int(input('Digite a idade do segundo homem: '))
m1 = int(input('Digite a idade da primeira mulher: '))
m2 = int(input('Digite a idade da segunda mulher: '))
soma = (max(h1,h2)) + (min(m1,m2))
produto = (min(h1,h2)) * (max(m1,m2))
print('A soma das idades do homem mais velho com a mulher mais nova é {}'.format(soma))
print('O produto das idades do homem mais novo com a mulher mais velha é {}'.format(produto))